/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErroresRouteImport } from './routes/errores'
import { Route as FormularioRouteImport } from './routes/formulario'
import { Route as InterpretarRouteImport } from './routes/interpretar'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PracticaRouteImport } from './routes/practica'
import { Route as SimulacroRouteImport } from './routes/simulacro'
import { Route as TemasIndexRouteImport } from './routes/temas/index'
import { Route as TemasSlugRouteImport } from './routes/temas/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErroresRoute = ErroresRouteImport.update({
  id: '/errores',
  path: '/errores',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioRoute = FormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const InterpretarRoute = InterpretarRouteImport.update({
  id: '/interpretar',
  path: '/interpretar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaRoute = PracticaRouteImport.update({
  id: '/practica',
  path: '/practica',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacroRoute = SimulacroRouteImport.update({
  id: '/simulacro',
  path: '/simulacro',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasIndexRoute = TemasIndexRouteImport.update({
  id: '/temas/',
  path: '/temas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasSlugRoute = TemasSlugRouteImport.update({
  id: '/temas/$slug',
  path: '/temas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errores': typeof ErroresRoute
  '/formulario': typeof FormularioRoute
  '/interpretar': typeof InterpretarRoute
  '/plan': typeof PlanRoute
  '/practica': typeof PracticaRoute
  '/simulacro': typeof SimulacroRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/temas/': typeof TemasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errores': typeof ErroresRoute
  '/formulario': typeof FormularioRoute
  '/interpretar': typeof InterpretarRoute
  '/plan': typeof PlanRoute
  '/practica': typeof PracticaRoute
  '/simulacro': typeof SimulacroRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/temas': typeof TemasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/errores': typeof ErroresRoute
  '/formulario': typeof FormularioRoute
  '/interpretar': typeof InterpretarRoute
  '/plan': typeof PlanRoute
  '/practica': typeof PracticaRoute
  '/simulacro': typeof SimulacroRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/temas/': typeof TemasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errores'
    | '/formulario'
    | '/interpretar'
    | '/plan'
    | '/practica'
    | '/simulacro'
    | '/temas/$slug'
    | '/temas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errores'
    | '/formulario'
    | '/interpretar'
    | '/plan'
    | '/practica'
    | '/simulacro'
    | '/temas/$slug'
    | '/temas'
  id:
    | '__root__'
    | '/'
    | '/errores'
    | '/formulario'
    | '/interpretar'
    | '/plan'
    | '/practica'
    | '/simulacro'
    | '/temas/$slug'
    | '/temas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErroresRoute: typeof ErroresRoute
  FormularioRoute: typeof FormularioRoute
  InterpretarRoute: typeof InterpretarRoute
  PlanRoute: typeof PlanRoute
  PracticaRoute: typeof PracticaRoute
  SimulacroRoute: typeof SimulacroRoute
  TemasSlugRoute: typeof TemasSlugRoute
  TemasIndexRoute: typeof TemasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errores': {
      id: '/errores'
      path: '/errores'
      fullPath: '/errores'
      preLoaderRoute: typeof ErroresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario': {
      id: '/formulario'
      path: '/formulario'
      fullPath: '/formulario'
      preLoaderRoute: typeof FormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interpretar': {
      id: '/interpretar'
      path: '/interpretar'
      fullPath: '/interpretar'
      preLoaderRoute: typeof InterpretarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica': {
      id: '/practica'
      path: '/practica'
      fullPath: '/practica'
      preLoaderRoute: typeof PracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacro': {
      id: '/simulacro'
      path: '/simulacro'
      fullPath: '/simulacro'
      preLoaderRoute: typeof SimulacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/': {
      id: '/temas/'
      path: '/temas'
      fullPath: '/temas/'
      preLoaderRoute: typeof TemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/$slug': {
      id: '/temas/$slug'
      path: '/temas/$slug'
      fullPath: '/temas/$slug'
      preLoaderRoute: typeof TemasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErroresRoute: ErroresRoute,
  FormularioRoute: FormularioRoute,
  InterpretarRoute: InterpretarRoute,
  PlanRoute: PlanRoute,
  PracticaRoute: PracticaRoute,
  SimulacroRoute: SimulacroRoute,
  TemasSlugRoute: TemasSlugRoute,
  TemasIndexRoute: TemasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
